---
# tasks file for ansible-role-rhel7-kvm-cloud-init

- name: Get a list of all instances
  virt:
    command: list_vms
  register: all_instances

- name: Teardown the VM
  import_tasks: teardown-vm.yml
  when: vm_recreate or vm_teardown

- name: Create VM data dir where store vm information
  file:
    state: directory
    path: "{{ vm_data_dir }}/{{ vm_name }}"
    force: yes
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown

- name: Deploy Base VM
  import_tasks: deploy-vm.yml
  when: not vm_teardown

- name: System Prep for Clone
  import_tasks: system-prep.yml
  when: not vm_teardown

- name: run post configuration
  import_tasks: post-config.yml
  when: not vm_teardown
