---
- name: ensure host is added to inventory
  lineinfile:
    path: "{{ inventory_file }}"
    regexp: "^{{ vm_name }}"
    backrefs: yes
    line: "{{ vm_name }}   ansible_host={{ vm_ip.stdout }} ansible_user={{ admin_user }}"
    insertafter: '^\[{{ inventory_group }}\]'
    state: present
  register: update_inventory
  when: update_inventory and vm_ip.stdout is defined

- name: refresh local static inventory
  meta: refresh_inventory

- name: get vm gateway from DHCP server
  shell: |
       ip route get 8.8.8.8|awk '/via/ {print $3}'
  delegate_to: "{{ vm_name }}"
  when: vm_ip.stdout is defined and vm_ip.stdout != ""
  changed_when: false
  register: vm_gateway

- name: Deploy ifcfg-{{ vm_nic.stdout }} to VM
  vars:
    - vm_ipaddress: "{{ vm_ip.stdout }}"
  template:
    src: ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ vm_nic.stdout }}"
  delegate_to: "{{ vm_name }}"
  when: vm_ip.stdout is defined and vm_ip.stdout != ""

- name: ensure cloud-init is removed
  yum:
    name: cloud-init
    state: absent
  delegate_to: "{{ vm_name }}"
  when: vm_ip.stdout is defined and vm_ip.stdout != ""

- name: restart {{ vm_name }} network service
  command: "systemctl restart {{ item }}"
  args:
    warn: no
  changed_when: false
  with_items:
    - network
    - NetworkManager
  delegate_to: "{{ vm_name }}"

- name: make sure resolv.conf is has entries
  find:
    paths: /etc/
    contains: '^nameserver ([0-9]{1,3}\.){1,3}[0-9]{1,3}$'
    patterns: "resolv.conf"
  register: resolv_conf_entries
  delegate_to: "{{ vm_name }}"
  become: yes
  when: vm_ip.stdout is defined and vm_ip.stdout != ""

- name: check for dns lookup
  command: getent ahosts www.cnet.com
  failed_when: false
  changed_when: false
  register: dns_lookup_result
  delegate_to: "{{ vm_name }}"
  become: yes
  when: vm_ip.stdout is defined and vm_ip.stdout != ""

- name: update {{ vm_name }} /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: (vm_ip.stdout is defined and vm_ip.stdout != "" and resolv_conf_entries.matched == 0)
        or
        (vm_ip.stdout is defined and vm_ip.stdout != "" and dns_lookup_result.rc == 2)
  delegate_to: "{{ vm_name }}"
