---

- name: scan remote for keys
  shell: |
      ssh-keyscan -H {{ vm_name }} \
                  {{ vm_ip }} \
                  {{ lookup('dig', vm_name ) }} | sort -u
  register: host_keys
  changed_when: false

- name: Update "~/.ssh/known_hosts" with discovered keys
  known_hosts:
    state: present
    name: "{{ item }}"
    key: "{{ host_keys.stdout_lines | select('search','^'~item~' .*$') | join('\n') }}"
  loop:
    - "{{ vm_name }}"
    - "{{ vm_ip }}"
    - "{{ lookup('dig', vm_name ) }}"
  failed_when: false

